-- =====================================================
-- PROYECTO: CAFETERÍA
-- ORACLE DATABASE 26ai
-- Authors: Almaraz García Beatriz, Martínez Ojeda Jonhatan Alexis, Raya Ramírez Angel Adrián
-- Description: Scripts que nos servirán para probar nuestras tablas, triggers, procedures y views. 
-- =====================================================
--Script para elimianr tablas (para pruebas)
DROP TABLE DETALLE_EXTRA CASCADE CONSTRAINTS;

DROP TABLE PRODUCTO_INSUMO CASCADE CONSTRAINTS;

DROP TABLE DETALLE_PEDIDO CASCADE CONSTRAINTS;

DROP TABLE SOLICITUD_INSUMO CASCADE CONSTRAINTS;

DROP TABLE PEDIDO CASCADE CONSTRAINTS;

DROP TABLE PRODUCTO CASCADE CONSTRAINTS;

DROP TABLE EXTRA CASCADE CONSTRAINTS;

DROP TABLE TIPO_LECHE CASCADE CONSTRAINTS;

DROP TABLE TEMPERATURA CASCADE CONSTRAINTS;

DROP TABLE TAMANO CASCADE CONSTRAINTS;

DROP TABLE CATEGORIA_PRODUCTO CASCADE CONSTRAINTS;

DROP TABLE INSUMO CASCADE CONSTRAINTS;

DROP TABLE CLIENTE CASCADE CONSTRAINTS;

DROP TABLE EMPLEADO CASCADE CONSTRAINTS;

--Triggers
DROP TRIGGER TRG_SUBTOTAL_DETALLE;

DROP TRIGGER TRG_TOTAL_PEDIDO;

DROP TRIGGER TRG_DESCONTAR_INSUMOS;

DROP TRIGGER TRG_REABASTECIMIENTO;

--Procedures
DROP PROCEDURE REGISTRAR_PEDIDO;

--Views
DROP VIEW VW_PRODUCTOS_MAS_VENDIDOS;

DROP VIEW VW_HISTORIAL_COMPRAS;

DROP VIEW VW_INSUMOS_BAJOS;

DROP VIEW VW_HORAS_AFLUENCIA;
